### ISSUE TITLE
Broader attachment support

### ISSUE THREAD

**Issue by yephny** [appml/neutrinote#11]
**Is your feature request related to a problem? Please describe.**
I like attaching documents, audio files, and videos to my notes, in-line.

**Describe the solution you'd like**
Implementing attachment support shouldn't be difficult as images can already be attached. I'm not asking for a document viewer inside of the app but an audio player like in Joplin would be quite useful, though it uses Chromium, so I wouldn't know if what I'm suggesting is feasible.

**Comment by ippocratis** [comment]
I also need this. 
@appml this issue opened a long time ago.
Could you please share your thoughts on it?
Simply close it if its not planed or too low in priority ?

Thanks.

**Comment by appml** [comment]
> I also need this. @appml this issue opened a long time ago. Could you please share your thoughts on it? Simply close it if its not planed or too low in priority ?
> 
> Thanks.

Had not been forgotten.  An experimental version of the feature may be included in the next build or so.

**Comment by ippocratis** [comment]
Just tried the attachment feature. 
Works as expected. 
Thanks

Keep uo

**Comment by appml** [comment]
> Just tried the attachment feature. Works as expected.
> 
> Thanks
> 
> Keep up

Great.  

(It's a bit experimental especially on older Android versions / custom ROMs.)
