### ISSUE TITLE
Open notes in markdown view by default

### ISSUE THREAD

**Issue by yephny** [appml/neutrinote#12]
**Is your feature request related to a problem? Please describe.**
I have a note with images and I just want to view it without doing any edits. Why am I supposed to hit the Markdown view icon and wait for images to load just to be able to view a note I've already opened? The same goes for any markdown formatting like lists.

**Describe the solution you'd like**
Open notes in markdown view by default.

**Additional context**
It doesn't make much sense to me to start with the editing mode only to then switch to markdown view just so that I can view a note with proper formatting.

**Comment by appml** [comment]
> What I'm suggesting is processing markdown first when a note is opened. If the user decides to edit the note, it should switch right back to editing mode with plain-text. There's no live markdown updates involved.

This can be attained by setting this app setting to true: 

**com.appmindlab.nano.pref_open_in_markdown**

For more details, please check out the documentation section [here](https://appml.github.io/nano/#hacks).

**Comment by yephny** [comment]
Thanks, I hope this becomes the default at some point.
