### ISSUE TITLE
Allow custom date format

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [appml/neutrinote#13]
**Is your feature request related to a problem? Please describe.**
I don't like the default date format for my locale (which is mm/dd/yy), and I always use yyyy-mm-dd.

**Describe the solution you'd like**
I think add a switch between default date format & custom one would be better for customization.

**Comment by Unknow0059** [comment]
Was this solved...?

**Comment by Liquid-Aristocracy** [comment]
> Was this solved, or what...? I can't find any datetime format options in nN.

[Here](https://appml.github.io/nano/#hacks), use `com.appmindlab.nano.pref_custom_date_format`.
