### ISSUE TITLE
[Question] Regarding file types and misc

### ISSUE THREAD

**Issue by smord6** [appml/neutrinote#16]
In the guide we have the following section:

> Advanced users may enable multiple text file types for neutriNote. 

In my app without doing the above hack, it appears I can already name a file "example.md" and my file manager recognizes it as a markdown file. So I'm confused at what the hack even does? 

Also, is there an option I'm missing that would enable to customize the font size in the notes list view? I'm aware that I can customize each note font.

I can't thank you enough for open sourcing this spectacular app and making it available on GitHub, and for the thorough documentation. Super amazing overall.

**Comment by appml** [comment]
> In the guide we have the following section:
> 
> > Advanced users may enable multiple text file types for neutriNote.
> 
> In my app without doing the above hack, it appears I can already name a file "example.md" and my file manager recognizes it as a markdown file. So I'm confused at what the hack even does?
By default, the app allows multiple text file types now.  While the option was used to be disabled by default, the behavior has been reversed as it seems more often than not the inquiries from new users is how to enable multiple file types.

> 
> Also, is there an option I'm missing that would enable to customize the font size in the notes list view? I'm aware that I can customize each note font.
> 
Yes, please check out this option from the Help document: **com.appmindlab.nano.pref_font_size_list**

> I can't thank you enough for open sourcing this spectacular app and making it available on GitHub, and for the thorough documentation. Super amazing overall.
Thank you for using the app.

**Comment by smord6** [comment]
Thank you!

**Comment by smord6** [comment]
@appml I already closed this, but the font option above appears to only change what font sizes I have to choose from for each individual note.

What I am really wanting is a way to make my whole list look larger. The whole note list, and not the font inside each individual note.
