### ISSUE TITLE
Settings>Mathematics doesn't respect adding "." in place of server to disable mathematics for better performance

### ISSUE THREAD

**Issue by smord6** [appml/neutrinote#17]
**Describe the bug**
App version 3.9.6 from F-Droid.
Per the guide:
> For users who do not use mathematics expressions, mathematics rendering can be disabled by entering a . under Mathematics in Settings. Markdown rendering should be faster with mathematics disabled.

The "." doesn't persist in the settings, instead the default server reappears in both the app settings and in the ...settings.txt file.

**To Reproduce**
1. Change mathematics server to .
2. Leave settings
3. Go back to settings and the server is filled out to default again

**Expected behavior**
The . should stay to disable mathematics

**Smartphone (please complete the following information):**
 - Device: Moto G Power
 - OS: Android 11

**Additional context**
I also tried changing it directly in the settings file, then restoring app data, and various combinations of restoring app data and backing up app data after modifying the file.

**Comment by smord6** [comment]
I noticed that if I clear the app data then deny the network permission during the initial setup, then it snips the address to https:// and basically fixes the issue.

In general, it seems that editing the settings file can be a little glitchy. The User Guide says to hit "restore app data" after editing it, which seems unintuitive. (I would almost rather have a separate option to hit that says Apply All Changes.)

Also applying changes doesn't always seem to work until I do some combination of "restore app data" and then "back up app data", or vice versa. And I'm not sure if that had anything to do with me using a "mirror" folder or what (something getting pulled when it should be pushed?). I got rid of my mirror folder so I will see if it helps.

Overall, maybe the user guide can be updated sometime to clarify the best situations to hit "restore app data" and "backup app data." And in what order to do them. I only see one reference to "backup app data" in the user guide.

Thanks again for the great app.

**Comment by smord6** [comment]
I am going to go ahead and close this since this issue became more about the user guide and less about the app. Feel free to reopen if you want. The initial issue has a tangible fix, just not what the user guide shows exactly (for me).

**Comment by appml** [comment]
> I am going to go ahead and close this since this issue became more about the user guide and less about the app. Feel free to reopen if you want. The initial issue has a tangible fix, just not what the user guide shows exactly (for me).

Sorry the instructions in the **User Guide** are outdated.  Instead of entering a `.`,  `https://` shoud be entered instead to switch off math rendering.  No need to carry out **Backup App Data** ➡️  **Restore App Data** (which is mainly for settings listed under [Hacks](https://github.com/appml/nano/blob/master/index.md#hacks)).

**User Guide** has also been fixed as of now.

Thanks.

**Comment by smord6** [comment]
Thanks again!
