### ISSUE TITLE
Widget shows ~neutrinote_app_data.txt file

### ISSUE THREAD

**Issue by SIRSteiner** [appml/neutrinote#23]
The first widget (with notes details) always shows the file ~neutrinote_app_data.txt
I think this is not a feature ;-)

Thank you

My device: Xiaomi Mi 9t Pro, A11

**Comment by appml** [comment]
Hi, please check if the neutrinote_app_data file has been starred.  Only starred notes are permitted to appear in the widget.  Thanks.

**Comment by SIRSteiner** [comment]
Sorry, I cannot find this file within the app, only at the widget
![IMG_20220210_115646](https://user-images.githubusercontent.com/3488638/153393090-b2cceed8-1b51-4937-bb4f-5270b983b206.jpg)
![IMG_20220210_115659](https://user-images.githubusercontent.com/3488638/153393108-16ed1fd3-6bbe-4637-8a40-eb22ec2a78e0.jpg)

**Comment by appml** [comment]
> Sorry, I cannot find this file within the app, only at the widget ![IMG_20220210_115646](https://user-images.githubusercontent.com/3488638/153393090-b2cceed8-1b51-4937-bb4f-5270b983b206.jpg) ![IMG_20220210_115659](https://user-images.githubusercontent.com/3488638/153393108-16ed1fd3-6bbe-4637-8a40-eb22ec2a78e0.jpg)

Settings -> Show Hidden

**Comment by SIRSteiner** [comment]
Okay. This happens if no notes are starred. Wouldn't it be better to show a messsge at the widget that only starred notes are shown at the widget in this case?

**Comment by appml** [comment]
> Okay. This happens if no notes are starred. Wouldn't it be better to show a messsge at the widget that only starred notes are shown at the widget in this case?

Thanks for the detailed report.  The bug will be fixed in version 4.0.4.
