### ISSUE TITLE
Widget gets no update if a note was changed

### ISSUE THREAD

**Issue by SIRSteiner** [appml/neutrinote#24]
Widget gets no update if a note was changed.
How to reproduce:
1. Click on a note at the widget to edit the note
2. Make some changes and go back to your home screen

Thank you

My device: Xiaomi Mi 9t Pro, A11

**Comment by appml** [comment]
Hi, the update cycle is controlled by Android for versions after Oreo.  In other words the power management of your phone's Android implementation will regulate the widget's update frequency.

**Comment by SIRSteiner** [comment]
That cannot be the reason because after 10 min and more the widget shows the unchanged note.
Also I use at the moment D Notes at the same device and there are no problems with the widget update.

**Comment by SIRSteiner** [comment]
Sorry, I don't know

**Comment by appml** [comment]
> Sorry, I don't know

Probably it is built for older versions of Android.  In newer versions, the widget update capability is rather [limited](https://developer.android.com/guide/components/broadcast-exceptions).

**Comment by SIRSteiner** [comment]
I see. But is there no other way? What about calendar widgets or music player widgets? They would useless if the widgets won't be updated.

**Comment by SIRSteiner** [comment]
Look at FairMail:
        minSdkVersion 21
        targetSdkVersion 31

The Widget (message list) gets always an update if something is changing.

**Comment by appml** [comment]
> Look at FairMail: minSdkVersion 21 targetSdkVersion 31
> 
> The Widget (message list) gets always an update if something is changing.

Good point about FairEmail.  The app is using the built-in broadcast as shown in the link shared above.  Widget update should work in upcoming v.4.0.5.

**Comment by appml** [comment]
> Now it works! You can close this issue. Thank you

Reason for closing: fixed in v4.0.5
