### ISSUE TITLE
Cursor is always rendered

### ISSUE THREAD

**Issue by SIRSteiner** [appml/neutrinote#25]
Please look at the screenshot.
![IMG_20220212_120839](https://user-images.githubusercontent.com/3488638/153709079-f9c026b3-eafa-4196-a85a-130af655b39f.jpg)

**Comment by appml** [comment]
> Please look at the screenshot. ![IMG_20220212_120839](https://user-images.githubusercontent.com/3488638/153709079-f9c026b3-eafa-4196-a85a-130af655b39f.jpg)

Reason for closing: the cursor is for retaining scrolling position in Markdown rendering.  Therefore not a bug.
