### ISSUE TITLE
No Markdown rendering within the widget

### ISSUE THREAD

**Issue by SIRSteiner** [appml/neutrinote#26]
Please look at the screenshot:

![IMG_20220212_122138](https://user-images.githubusercontent.com/3488638/153709232-8db1bc64-6a08-4a2c-988f-074cc0c5362c.jpg)

**Comment by appml** [comment]
> Please look at the screenshot:
> 
> ![IMG_20220212_122138](https://user-images.githubusercontent.com/3488638/153709232-8db1bc64-6a08-4a2c-988f-074cc0c5362c.jpg)

Close reason: not a bug.  Should be considered a feature request instead.
