### ISSUE TITLE
Go to next/previous search result (Feature request)

### ISSUE THREAD

**Issue by Gabr-F** [appml/neutrinote#30]
It appears that at the moment the only way to find the individual results of a search is to scroll through an entire file looking for highlighted parts.

That might be somewhat ok for short files, but definitely not for longer ones.

I think there should be the simple thing that pretty much all editors have, namely "goto next result" and a "goto previous result" buttons.
And while we're at that, a closely related (it's usually placed next to these buttons) useful thing is the indication of the amount of occurrences and the number of the current one

**Comment by appml** [comment]
To scroll through search hits, just use the search button in the editor to navigate.  Or visit the [documentation](https://appml.github.io/nano/#gestures) for navigation gestures.
