### ISSUE TITLE
Feature request: A quicker way to delete the currently open file

### ISSUE THREAD

**Issue by Gabr-F** [appml/neutrinote#31]
I often need to keep something in a temporary file for a very short time, so I'd like to delete it quickly as soon as I don't need it anymore, and the realization/confirmation that I don't need it anymore occurs very offer while I have it open and I'm checking its contents.

So the current only way to do it, namely having to go back to the files' list, selecting the file and tapping the delete button is quite awkward, so much that I have now about 120 "New note"s that I never manage to get back to check and delete or rename.

By "very short time" I mean from a few minutes to a few days.

I don't know how widespread in the user base my need is, but since it might be solved by a simple addition to the editing screen's menu I hope you'll decide to address it.

By the way mine is probably a quite frequent way to use editors, since most apps on many phones lose their state extremely easy, and it's thus **very** unwise to write long texts in a random app (e.g. a Fenix browser).

An alternative method is to always reuse the same temporary file, maybe naming it so that it stays at the top of the files' list. 
I *do* also do that, but I found out that it gets awkward, in that if you have unrelated stuff in the same file you then have to look for it every time, and copy/pasting gets a lot more awkward (in a dedicated file you can simply and quickly do a "select all").

I think my preferred solution would be a delete button (in the editing/viewing screen), but an item in the menu would be ok too.

By the way, this is a feature useful in normal computers' text editors too, but a lot less needed since there it's a lot more likely that you'll already have a file manager open at the desired path (and it's easier to do anything in general).

If it's of any importance, this feature is of a little less priority to me than #29 and #30.

**Comment by appml** [comment]
If you need a temporary file, look under [Effortless Edit](https://appml.github.io/nano/#editorless) in the documentation, especially the experimental feature called `neutriNote Scrapbook.txt`.

**Comment by Gabr-F** [comment]
> If you need a temporary file, look under [Effortless Edit](https://appml.github.io/nano/#editorless) in the documentation, especially the experimental feature called `neutriNote Scrapbook.txt`.

Ah that's somewhat interesting! It took me a while to find the notification (for some reason it stays below dozens of others, even after force-stopping and restarting neutriNote) but I found it and it seems to work.

However it has almost nothing to do what I was speaking about; the things that I want to edit in a reliable app such as neutriNote are long texts, while the notification doesn't even seem to allow to enter more than a line at a time!

And as I mentioned multiple files *are* needed for my use case, everything in a single one is too awkward.

Honestly your dismissal and closing of the issue seemed a bit too hasty!
