### ISSUE TITLE
Feature request: Auto dark/light theme switching

### ISSUE THREAD

**Issue by Gabr-F** [appml/neutrinote#32]
Now that it's summer 🙂 I found out it's convenient  to frequently toggle the phone's dark mode.

Many apps are able to adapt automatically to the phone's setting, neutriNote currently isn't.

I *have* been trying the "Ambient Glow" feature, but if it has any effect on my phone it surely is not enough.

So it would be nice to e.g. have an "auto" option among the selectable themes.

At least at first it's not necessary to let the user specify which of the two dark themes to use, you can just pick one of them yourself, but of course it would be even better to be able to specify it (e.g. with an "auto switch" checkbox that makes come out one or two RadioGroups to select the wanted dark and maybe even the light theme - for flexibility and semplicity you might simply allow any theme to be chosen as the "dark" or "light" one, at most with an icon hinting which kind it's supposed to be - ok this might be overkill with just three themes 🙂) .

I consider this feature request of minor impact.

**Comment by appml** [comment]
System light / dark mode support will be included in v4.1.5.  Thanks.

**Comment by Gabr-F** [comment]
Great news, thanks!!! 👏

May 27, 2022 12:04:49 AppML ***@***.***>:
