### ISSUE TITLE
Crash upon creating a new note (+ button)

### ISSUE THREAD

**Issue by projjalm** [appml/neutrinote#33]
whenever I try to create a new note, or whatever gets created by clicking + button, the app instantly crashes without any "x app has stopped working" message.
at first I thought it was because of removing some system apps using debloater... but idk much about dependencies in android so I just reported this issue.
you can recreate this by initializing the app and specifying a local repository, and then clicking the + button.
am I missing something? or it's the app glitching out?
I'm running LineageOS 13 with kernel 3.10.72 on Lenovo tab3 710i

**Comment by projjalm** [comment]
the storage permission is turned on already and in addition, I gave it camera and location permission as well... but it still crashes. since no-one else is having this issue, my best guess is whichever library or android system app, this app calls on clicking that button, got removed when carelessly debloated my device. thanks for your reply :)

**Comment by appml** [comment]
Likely a result of debloating.  Thus closed.
