### ISSUE TITLE
Scrollbar Passive

### ISSUE THREAD

**Issue by glow12121** [appml/neutrinote#35]
Scrollbar's behavior seems passive, that is one cannot tap on it and slide to scroll the text up and down.

It could be that my fingers are too big though :)

I am talking about the little blue thing in the bottom right corner here:

![Screenshot_20220629-154838_neutriNote](https://user-images.githubusercontent.com/29035180/176440916-20537deb-a8be-4ef0-b40b-69ef79eb34e1.png)

**Comment by appml** [comment]
Hello--

I don't understand.  It works no differently than any standard scroll bar.  What's the issue here?

**Comment by glow12121** [comment]
I tried to record a video to show that I sort of cannot catch the scroll line to drag it. https://www.dropbox.com/s/igmi9yj3dd1bz5y/vidma_recorder_03072022_193046.mp4?dl=0

**Comment by glow12121** [comment]
Maybe it could be a general Androif ptoblem. I noticed I cannot use the sctollbar in the browser either (it is Vivaldi, Chrome-based).

Here a developer reported the same bug: https://stackoverflow.com/questions/68072431/cannot-scroll-using-scrollbar-in-android

**Comment by appml** [comment]
Closed due to issue pertaining to Android's built in functionality.  

For other navigation aids, please see documentation.

**Comment by glow12121** [comment]
I've just noticed that the scrollbar is active when the app is displaying the notes list. I can drag it up and down.
