### ISSUE TITLE
Add support for storage-access-framework

### ISSUE THREAD

**Issue by Haze-sh** [appml/neutrinote#36]
**Is your feature request related to a problem? Please describe.**
This would make NeutriNote compatible with DAVx5 and webdav in general.

**Describe alternatives you've considered**
Import and export functionality isn't enough in this context even by using the mirror functionality.

**Comment by appml** [comment]
Mirror when available already provides efficient continuous sync to SAF in the background (there is no need to issue import / export separately).

https://appml.github.io/nano/#mirror

HTH

**Comment by Haze-sh** [comment]
Thank you!
