### ISSUE TITLE
Feature request: settings option to open new files in preview/markdown view by default

### ISSUE THREAD

**Issue by NathanC** [appml/neutrinote#38]
It'd be nice to have a setting where, when enabled, opening a note will by default show it in the preview mode. This would match the behavior of some previous note taking apps I've used before.

I think it makes sense because more frequently I'd consume old notes vs editing them.

Do you think it would be good to select which extensions to open in this mode, or just have it be a binary toggle? It might be good to have plain .txt skip this option.

(I might take a stab at adding this feature if it seems acceptable to you)

**Comment by appml** [comment]
The feature already exists.  Please look for `com.appmindlab.nano.pref_open_in_markdown` under this section:

https://appml.github.io/nano/#hacks

**Comment by appml** [comment]
Feature already exists.
