### ISSUE TITLE
Can't push to mirror

### ISSUE THREAD

**Issue by Haze-sh** [appml/neutrinote#39]
When I push my local changes to mirror it doesn't sync. I can push new created notes but they are pushed as blank notes.
I can pull as expected so the problem isn't server side.

**Comment by appml** [comment]
Hi, has Auto Mirror been activated under Settings?

![Screenshot_20220803-160951](https://user-images.githubusercontent.com/7504229/182699915-7b723d37-d764-4ef6-9d9b-d47e14e4cd87.png)

If it does, try Force Sync.

![Screenshot_20220803-161106](https://user-images.githubusercontent.com/7504229/182700166-a5688a8c-7fbe-4f77-acb6-6458a859c008.png)

HTH

**Comment by Haze-sh** [comment]
Yes Auto Mirror is activated. Force Sync reverts my local changes!

**Comment by appml** [comment]
Hmmm...  What is your setup (e.g., repo path, paths to backup folder and mirror), and Android version?

**Comment by Haze-sh** [comment]
Local repo path is the default: /storage/emulated/0/Android/data/com.appmindlab.nano/fi...
Back up folder is a directory on a WebDav server and mirror is a sub-directory to it.

**Comment by appml** [comment]
What is the path when you toggle the button as in the screenshot?

![Screenshot_20220810-102522](https://user-images.githubusercontent.com/7504229/183926845-284e454e-2a00-4331-8627-62ff68ca275e.png)

**Comment by Haze-sh** [comment]
WebDAV mount
