### ISSUE TITLE
Use the system theme by default

### ISSUE THREAD

**Issue by xmha97** [appml/neutrinote#41]
Please use the system theme by default.
![Screenshot_2022-08-12-04-43-42-716_com.appmindlab.nano.jpg](https://user-images.githubusercontent.com/23485114/184263007-987063c5-a843-40f5-b8e6-012e11b5c464.jpg)

**Comment by appml** [comment]
System theme is the default now.  Thanks.

**Comment by xmha97** [comment]
There are still problems.  After installation, the Android theme is used but it is selected in the "Day" settings, which means that if we change the settings, the Android theme will no longer be used!
Sorry for my bad English 🥲

https://user-images.githubusercontent.com/23485114/189638481-90592bc4-e4ae-4238-acbb-8367653bae54.mp4
