### ISSUE TITLE
What does each field in ~neutrinote_app_data.txt mean?

### ISSUE THREAD

**Issue by jamesWalker55** [appml/neutrinote#43]
Here is an example line:

```
New Note (10):0:-1::1575367087046:0.0:0.0:1575367087046:1536793458000::
```

From what I can tell, the first field is the note title, and the last field is the last modified time of the note. However I can't really tell what the other fields mean?

**Comment by appml** [comment]
Look under line 4749:

https://github.com/appml/neutrinote/blob/95de756141b28247eecf49b8079486379d943f99/app/src/main/java/com/appmindlab/nano/MainActivity.java?utm_source=pocket_mylist#L4731

Hope this helps.

**Comment by jamesWalker55** [comment]
Thanks, that solves it.

As of this writing, the fields delimited by ':' are:

```
entry.getTitle()
entry.getStar()
entry.getPos()
entry.getMetadata()
entry.getAccessed().getTime()
entry.getLatitude()
entry.getLongitude()
entry.getCreated().getTime()
entry.getModified().getTime()
```
