### ISSUE TITLE
Bug: Add FLAG_(IM)MUTABLE for pending intents in A12+

### ISSUE THREAD

**Issue by proItheus** [appml/neutrinote#44]
A12+ requires FLAG_(IM)MUTABLE for all pending intents. Now the app will throw an error when creating widgets.

**Comment by appml** [comment]
Hmmm... Can't reproduce the error on A12+ on multiple launchers.  Any info about your launcher?  Tired remove and re-add the widget?

**Comment by proItheus** [comment]
Ahh, my fault. The `note browser` widget works fine , while `new note` widget throws an error.

**Comment by appml** [comment]
Should have been fixed in the next build (v4.2.4)

**Comment by appml** [comment]
Resolved.
