### ISSUE TITLE
Can't see this app on pCloud open with dialog for MD files

### ISSUE THREAD

**Issue by xmha97** [appml/neutrinote#45]
Hi
My notes are stored on pCloud
Now I want to see them but I can't find this app on open with dialog
![Screenshot_2022-09-10-13-30-51-615_android.jpg](https://user-images.githubusercontent.com/23485114/189476635-b2d71c3a-fb54-4c3c-bcfc-1e3220a21515.jpg)

**Comment by appml** [comment]
Please ask pCloud developers to add neutriNote to the selection of permitted apps (a.k.a **queries**)  under their manifest file.  Thanks.

**Comment by xmha97** [comment]
This is a problem on your part, otherwise this app should not have been displayed:
https://github.com/wbrawner/SimpleMarkdown

**Comment by appml** [comment]
https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9

**Comment by appml** [comment]
Please try and see if you can find neutriNote when opening a md file using apps like a file explorer.   

When I opened.md under several file explorers, each time neutriNote appears in the app list:

![Screenshot_20220911-072819](https://user-images.githubusercontent.com/7504229/189525019-0e477528-b758-47e5-a9d4-828d39caf1e8.png)

![Screenshot_20220911-073218](https://user-images.githubusercontent.com/7504229/189525281-3bd26663-a688-4ff4-998d-c1f201bff71f.png)

**Comment by appml** [comment]
@xmha97 Please give the new build [v4.2.4a](https://github.com/appml/neutrinote/releases/tag/v4.2.4a) a try.  Thanks.

**Comment by xmha97** [comment]
Thanks but there is this issue:
https://github.com/appml/neutrinote/issues/46

**Comment by appml** [comment]
Resolved
