### ISSUE TITLE
Default theme issue

### ISSUE THREAD

**Issue by xmha97** [appml/neutrinote#47]
There are still problems.  After installation, the Android theme is used but it is selected in the "Day" settings, which means that if we change the settings, the Android theme will no longer be used!
Sorry for my bad English 🥲

https://user-images.githubusercontent.com/23485114/189638481-90592bc4-e4ae-4238-acbb-8367653bae54.mp4

_Originally posted by @xmha97 in https://github.com/appml/neutrinote/issues/41#issuecomment-1243578040_

**Comment by appml** [comment]
Using v4.2.4b?

**Comment by appml** [comment]
Fixed in new build.  Thus closed.
