### ISSUE TITLE
Why does it connect to some server? Can it not be used offline?

### ISSUE THREAD

**Issue by mYnDstrEAm** [appml/neutrinote#48]
I don't have any online sync enabled. I just installed the app and clicked the dialog window. Now, the NetGuard firewall shows me the app tries to connect to some server many times. Why is that? And why can't it be used completely offline? I could not find any settings to make it offline-only either.

**Comment by appml** [comment]
As shown in the code, the app is ompletely offline unless you enable math rendering or other features such as Python, Vue, etc.  In those cases, cache will always be checked first.

**Comment by appml** [comment]
Opt out provided during setup.  Thus closed.
