### ISSUE TITLE
It should not connect to some servers (despite math disabled)

### ISSUE THREAD

**Issue by mYnDstrEAm** [appml/neutrinote#50]
**Describe the bug**
Also see #48

Can it not be used offline? I **don't** have any online sync enabled. I just installed the app and clicked the dialog window. Now, the NetGuard firewall shows me the app tries to connect to some server many times. Why is that? And why can't it be used completely offline? I could not find any settings to make it offline-only either.

Here's what I did:

**To Reproduce**
1. Install from Playstore and tap on open
2. It asks "Math Formulas Network access required when processing math formulas for the first time. Proceed?"
3. I press **DENY**
4. It asks "Local Repistory Setup By creating a local repository, your notes will automatically be mirrored as files. the repository would also make syncing with P2P or cloud providers easier".
5. This is a very bad prompt, please fix that too. What exactly is it asking me about...would confirming anything already enable some syncing functionality? I press QUIT
6. I restart the app the prompt of 4 displays again, I select USE DEFAULT
7. It asks "In the next screen, you will be asked to grant neutriNote access to device storage. The permission is required for neutriNote to function properly."
8. This is a very bad requirement: other note-taking apps don't require this and it should only be required if the user actually needs it. I enable storage access anyway.
9. I restart the app because it asks me to.
10. The prompt of step 4 displays again.
11. This is a bad thing, the prompt should only display once. I select USE DEFAULT again.
12. I restart the app, finally no prompt is shown anymore.

During the whole setup (I think after step 1 but at least after step 6) as well as after step 12, neutrinote tries to connect to some servers.

This can be checked with the connection protocol in the NetGuard firewall (where I have its Internet access blocked).

**Expected behavior**
* Only step 1 should be required and the default mode should be offline. Any prompts should display only once, it should not require full device storage access and maths should only be enabled when needed or manually in the options.
* **No Internet connection**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Version: v4.2.4b (latest in playstore)

**Smartphone (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by appml** [comment]
The prompts you mentioned are for the purpose of granularity and users only need to interact with once during the initial setup.

Attached is the log screen from Netguard when neutriNote is in use:
![Screenshot_20220930-223211](https://user-images.githubusercontent.com/7504229/193379715-c0bfb3fe-6241-4b59-8dfe-fcd011d420d3.png)

Hope this helps.

**Comment by appml** [comment]
Also note that the version from Fdroid is not the same as the version from Play Store.  Play Store is using Google service such as ML to support functions like OCR, Fdroid version does not come with built-in Google backed features.

**Comment by mYnDstrEAm** [comment]
I don't think there is a prompt and disclaimer that the playstore version connects to some servers. I have many entries in the netguard protocol after installing. It tries to connect to `142.250.179.138` and `142.250.179.202` and `216.58.214.10` and many other IPs

**Comment by appml** [comment]
> I don't think there is a prompt and disclaimer that the playstore version connects to some servers. I have many entries in the netguard protocol after installing. It tries to connect to `142.250.179.138` and `142.250.179.202` and `216.58.214.10` and many other IPs

There is not mentioned since Google grants the permission by default.  Like mentioned in my last reply as well as in the Help file, the connection in the regular version is for OCR which is provided through Google  (for server information see screenshots below).  That's why there is a distinction in name between the two builds {btw, this issue tracker is for reporting issues of neutriNote CE).

![Screenshot_20221001-062224](https://user-images.githubusercontent.com/7504229/193404848-ec03d000-d581-46e9-9e08-4fe495e81302.png)

Hope this helps
