### ISSUE TITLE
Trash bin folder

### ISSUE THREAD

**Issue by h-cspu** [appml/neutrinote#51]
I'm trying to enable the trash bin folder with

com.appmindlab.nano.pref_keep_deleted_copies|true

in /storage/emulated/0/neutriNote/~neutrinote_settings_data.txt

For testing purposes I also added

com.appmindlab.nano.pref_max_deleted_copies_age|30

(I applied the changes with "Restore App Data")

But the files are getting deleted.

I think the location for the trash bin folder is "my repository path"/trash_bin. Even if I create this folder manually, the files are getting deleted.

I'm running Android 7 (LineageOS 14) on my device.

**Comment by appml** [comment]
Thanks.  Fixed in v4.2.5.

**Comment by h-cspu** [comment]
Fixed. Thanks!
