### ISSUE TITLE
table alignment does not work

### ISSUE THREAD

**Issue by h-cspu** [appml/neutrinote#52]
Version 4.2.4b

In the example of "PHP Markdown Extra" (https://michelf.ca/projects/php-markdown/extra/#table)

\| Item | Value |
\| --- | ---: |
\| Computer | $1600 |
\| Phone | $12 |
\| Pipe | $1 |

all cells are rendered left-aligned. The right column should be right aligned.

**Comment by appml** [comment]
Thanks.  Fixed in v4.2.5.

**Comment by h-cspu** [comment]
Fixed. Thanks.
