### ISSUE TITLE
3-dot "Burger Menu" is empty in Edit Mode and Markdown View in landscape mode

### ISSUE THREAD

**Issue by h-cspu** [appml/neutrinote#54]
Version 4.2.5
OS: Android 7 (LineageOS 14)

Steps to reproduce:
1. create a new note
2. write text: foo
3. rotate device so that neutriNote rotates to landscape view
4. press the 3-dot-Button

The menu is empty.

5. press Button "Markdown View"
6. press the 3-dot-Button

The menu is also empty.

**Comment by appml** [comment]
Hmmm...  Can't reproduce

![Screenshot_20221006-090859](https://user-images.githubusercontent.com/7504229/194327971-6f339b3f-3231-48bb-83fb-feceaca5ba10.png)

**Comment by h-cspu** [comment]
Edit Mode:
![Screenshot_20221007-051747_edit_mode](https://user-images.githubusercontent.com/11554025/194480235-01df828b-3756-4567-b703-fcf3343aa898.png)

Markdown View:
![Screenshot_20221007-051802_markdown_view](https://user-images.githubusercontent.com/11554025/194480308-91d0e127-bdc6-420e-8fbc-7c6d9e86fcac.png)

**Comment by appml** [comment]
This is most likely a bug in the theme provided by Android.  Sorry nothing I can do about it.

**Comment by appml** [comment]
A workaround is to switch to another theme.

**Comment by appml** [comment]
Fixed in 4.2.6b

**Comment by h-cspu** [comment]
Fixed. Thanks!
