### ISSUE TITLE
landscape mode: last line(s) of text in Markdown View only visible when Title is not shown

### ISSUE THREAD

**Issue by h-cspu** [appml/neutrinote#55]
Version 4.2.5

Steps to reproduce:
1. create a new note
2. write as many lines that you must scroll in landscape mode to get to the end of the text
3. press Button "Markdown View"
4. Scroll to the bottom
5. toggle Title

Only when the title is not shown, the complete text is visible.

**Comment by h-cspu** [comment]
> Can't reproduce. Please check to see if it has any hidden blank characters at the end of the text.

I wrote the note in neutriNote for this example. So I don't think that there are blanks at the end of the text.

In both screenshots the scroll position is at the bottom.

Title visible:
![Screenshot_20221007-051251](https://user-images.githubusercontent.com/11554025/194481271-85f76a21-0083-4dd0-a644-1e44c7370f49.png)

Title not visible:
![Screenshot_20221007-051302](https://user-images.githubusercontent.com/11554025/194481339-4c46d9ab-c59d-4176-a672-e06658c631f0.png)

In case it's important, I'm using the font "Roboto Mono Regular".
![Screenshot_20221007-051304](https://user-images.githubusercontent.com/11554025/194481550-697ef1a7-cf7f-4da5-89f5-3583d0d070e2.png)

**Comment by appml** [comment]
This is most likely due to the combination of Android's webview component with the app's older generation layout so that certain features will continue to work.  Sorry beyond my resources to remedy this.  Looking for developers who may be interested in contributing to this project as always.

**Comment by appml** [comment]
Fixed in 4.2.6b

**Comment by h-cspu** [comment]
Fixed. Thanks!
