### ISSUE TITLE
Rendering of images really slow

### ISSUE THREAD

**Issue by AlexDerk** [appml/neutrinote#6]
**Describe the bug**
Even when having only two larger images (about 6mb) attached in a note, rendering speed goes really down and navigation (swipe up/down) becomes nearly impossible on Android.

**Expected behavior**
Smooth scrolling with multiple images in a note.

Greetings
Alex

**Comment by AlexDerk** [comment]
There are no Developer Options in my Settings... and I can't find any reference to them in the documentation.

Btw, I got the app from F-Droid.

**Comment by appml** [comment]
> There are no Developer Options in my Settings... and I can't find any reference to them in the documentation.
> 
> Btw, I got the app from F-Droid.

Have you used steps like [these](https://developer.android.com/studio/debug/dev-options#enable) to enable Developer Options?

**Comment by AlexDerk** [comment]
Ah, you meant in Android! I thought you meant the Android app...

In the Developer Options I only have Android System Webview 92.0.4515.159 available. 
I'm on a Oneplus 6t.

**Comment by wizpig** [comment]
Opening the markdown file (with images) from within the Webinterface of Nextcloud on the same Android device (i.e. using the same WebView?), everything runs super smooth.

Some further background Infos:
- OnePlus 6t running Android 10 
- Neutrinote  V3.8.3

**Comment by wizpig** [comment]
> Opening the markdown file (with images) from within the Webinterface of Nextcloud on the same Android device (i.e. using the same WebView?), everything runs super smooth.
> 
> Some further background Infos:
> 
> * OnePlus 6t running Android 10
> * Neutrinote  V3.8.3

Sorry, I wrote here from a different account. 
wizpig  == AlexDerk is true.

**Comment by appml** [comment]
> > Opening the markdown file (with images) from within the Webinterface of Nextcloud on the same Android device (i.e. using the same WebView?), everything runs super smooth.
> > Some further background Infos:
> > 
> > * OnePlus 6t running Android 10
> > * Neutrinote  V3.8.3
> 
> Sorry, I wrote here from a different account.
> wizpig == AlexDerk is true.



> Opening the markdown file (with images) from within the Webinterface of Nextcloud on the same Android device (i.e. using the same WebView?), everything runs super smooth.
> 
> Some further background Infos:
> 
> * OnePlus 6t running Android 10
> * Neutrinote  V3.8.3

I'm unfamiliar with Nextcloud so really uncertain if it is using the Webview provided by Android.

Nonetheless, see if v3.8.4 solves your problem.

**Comment by appml** [comment]
Fixed in v3.8.4

**Comment by appml** [comment]
Addressed in v3.8.4
