### ISSUE TITLE
ListView theme is light on dark mode

### ISSUE THREAD

**Issue by xmha97** [appml/neutrinote#61]
Hi,
The ListView theme is light on dark mode.
![Screenshot_2022-11-29-00-48-33-684_com.appmindlab.nano.jpg](https://user-images.githubusercontent.com/23485114/204383305-ce63a9b6-70b2-42d3-9124-02fbd1566d52.jpg)
Please fix this issue and improve dark mode.
Thanks.

**Comment by xmha97** [comment]
No,
(My device is dark)
1. I installed the app
2. I added a few notes
3. See this issue

**Comment by appml** [comment]
What's your theme settings?

**Comment by xmha97** [comment]
The theme is system.
Watch this video:

https://user-images.githubusercontent.com/23485114/204845013-6c074a3a-59f2-40ef-831f-e255d1083f08.mp4

**Comment by appml** [comment]
What is the app version?

**Comment by xmha97** [comment]
> What is the app version?
neutriNote CE v4.3.1.b

> What is the Android version?
Android 12 (Snow Cone)

> What is the phone model?
Xiaomi 11T

**Comment by appml** [comment]
Unable to reproduce the problem on my test devices.  What happens if you force Dark Theme within the app?  What happens if forcing Dark Mode via Android Settings?

**Comment by appml** [comment]
Not reproducible across test devices.
