### ISSUE TITLE
can't change local repository path

### ISSUE THREAD

**Issue by gesu92** [appml/neutrinote#66]
**Describe the bug**
Can't change the local repository path, when install the app this don't let me select the path for the local repository, and whe it's already install can't change the path from settings menu, only show a notification with the current path when I tap it.

**To Reproduce**
1. Go to settings menu.
2. tap on "Local repository path"

**Expected behavior**
Open a select box for a path when I tap it.

**Screenshots**
On tap in "Local Repository path"
![Screenshot_20230325-112636](https://user-images.githubusercontent.com/87961082/227723366-5436ac47-6c15-4abf-8cf7-08e0f2c0ad7a.png)

**Smartphone (please complete the following information):**
 - Device: moto x4
 - OS: Android 9
 - Version 4.3.5.b,( still happen in 4.3.4.b on downgrade)

**Additional context**
This is not happen in my tablet with android 7

**Comment by appml** [comment]
Please see the documentation for the restrictions imposed by Android post-Oreo.  Thus closed.
