### ISSUE TITLE
In-Device Fonts (Custom font)

### ISSUE THREAD

**Issue by chromer030** [appml/neutrinote#69]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Choosing between fonts that are present in user device, both system fonts and storage fonts (user fonts)

**Describe alternatives you've considered**

**Additional context**
https://github.com/gsantner/markor has this feature, as both projects are in java, maybe codebase could help.

**Comment by appml** [comment]
Due to the unique structure of the app, the solution cannot be directly adopted.

However to use device's default font in the app (besides Markdown view), pls see the section: 

https://appml.github.io/nano/#externalfonts

HTH

**Comment by chromer030** [comment]
So if there is a workaround for this, we can close the issue.
Thanks very much.
