### ISSUE TITLE
Export Format. Is this normal..?

### ISSUE THREAD

**Issue by HaZe5657** [appml/neutrinote#73]
**Describe the bug**
There's no format to choose from when exporting.

**To Reproduce**
Open the note created.
3 dots up top.
Export.

**Expected behavior**
A dialog with formats to choose from, specify.

**Screenshots**
![Screenshot_20240208-224449](https://github.com/appml/neutrinote/assets/85792795/89383a8f-af27-4b52-86f4-7a152efd23ff)

**Comment by appml** [comment]
Thanks for reporting.  Remedy in next build.

**Comment by appml** [comment]
Fixed
