### ISSUE TITLE
Help menu still links to old repo URLs

### ISSUE THREAD

**Issue by GfEW** [appml/neutrinote#74]
**Describe the bug**
In Neutrinote CE 4.5.1b for Android, the `Help` menu item opens https://appml.github.io/nano/ . Whilst the contents of that documentation is impressingly comprehensive and helpful indeed, it's confusing the URL still reads "nano" and, by "View on GitHub", still directs to the abandoned repository https://github.com/appml/nano. 

**To Reproduce**
1. In Neutrinote CE for Android, open the "burger" menu in the upper left corner.
2. Tap at `Help` (i. e. the second last item) and see which web page is opened in your browser.
3. On that page, tap `View on GitHub` and see where that takes you.

**Expected behavior**
* In step 3., the button `View on GitHub` should direct to the current repository, https://github.com/appml/neutrinote .
* On a side note, the github.io URL should also be changed, so in step 2., `Help` opens https://appml.github.io/neutrinote .

**Comment by saelim** [comment]
"View on GitHub" link in the help file should have been fixed now.

Thanks.
