### ISSUE TITLE
Cannot launch apps using text-expanding

### ISSUE THREAD

**Issue by Lidikno** [appml/neutrinote#77]
First of all, kudos for the unique and intelligent approach of your app!

As the title suggests, I can't launch other apps (namely: termux, calculator ++, phiola) by expanding the assigned shortcut -I get an "unexpected error" message. Am I missing something here or is it a bug?

Pixel 6
A14 stock
nN CE v4. 5.1c

Thanks

**Comment by appml** [comment]
Not a bug.  App launching has been restricted since A11.  

Note that apps to be launched in neutriNote must now be explicitly declared [here](https://github.com/appml/neutrinote/blob/620798320695cfd1943ae270e21d3fe3c65814c2/app/src/main/AndroidManifest.xml#L20).

**Comment by Lidikno** [comment]
Thank you for replying and pointing out a solution.
