### ISSUE TITLE
Default to markdown view 

### ISSUE THREAD

**Issue by ippocratis** [appml/neutrinote#78]
**Is your feature request related to a problem? Please describe.**
It makes more sense to want to preview already edited notes and only hit edit if you want to re-edit them 

**Describe the solution you'd like**
Opening a note should default to markdown view. 
Creating a note to edit mode

**Describe alternatives you've considered**
Well, I just tap on the markdown view button each time I open any note.

**Additional context**
None.
Thanks for the amazing app.

**Comment by appml** [comment]
Use this flag:

com.appmindlab.nano.pref_open_in_markdown

[See also](https://appml.github.io/nano/#hacks)

**Comment by ippocratis** [comment]
> Use this flag:
> 
> com.appmindlab.nano.pref_open_in_markdown
> 
> [See also](https://appml.github.io/nano/#hacks)

Thanks for pointing to the right place in the documentation. 

Missed that.

Closing
