### ISSUE TITLE
Auto backup to mirror is stale

### ISSUE THREAD

**Issue by ippocratis** [appml/neutrinote#80]
**Describe the bug**
Automatic background backup never finishes.
The process in the notification that shows its progress is  stale.
If I tap on it the backup exits unfinished
**To Reproduce**
Enable backup/mirror and autosave.
When phone is iddle it should start the procces

**Expected behavior**
It should complete the backup

**Screenshots**
-

**Desktop (please complete the following information):**
 - 

**Smartphone (please complete the following information):**
 - Device: poco x5 pro 5g
 - OS: Android 14 crdroid rom
 - Browse -
 - Version 4.5.2b

**Additional context**
Manually initiating an export completes successfully

**Comment by appml** [comment]
Is Power Saving mode on?

**Comment by ippocratis** [comment]
No

My ~neutrinote_settings_data

com.appmindlab.nano.pref_auto_save|true
com.appmindlab.nano.pref_copy_attachments_to_repo|true
com.appmindlab.nano.pref_custom_filters|all;starred;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Y;Z
com.appmindlab.nano.pref_incremental_backup|true
com.appmindlab.nano.pref_lazy_update|false
com.appmindlab.nano.pref_location_aware|false
com.appmindlab.nano.pref_lux|false
com.appmindlab.nano.pref_math_url|https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
com.appmindlab.nano.pref_max_backup_count|2
com.appmindlab.nano.pref_open_in_markdown|true
com.appmindlab.nano.pref_order_by|modified
com.appmindlab.nano.pref_order_by_direction|DESC
com.appmindlab.nano.pref_preview_mode|off
com.appmindlab.nano.pref_show_hidden|true
com.appmindlab.nano.pref_theme|system
❘

**Comment by appml** [comment]
> No
> 
> My ~neutrinote_settings_data
> 
> com.appmindlab.nano.pref_auto_save|true
> com.appmindlab.nano.pref_copy_attachments_to_repo|true
> com.appmindlab.nano.pref_custom_filters|all;starred;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Y;Z
> com.appmindlab.nano.pref_incremental_backup|true
> com.appmindlab.nano.pref_lazy_update|false
> com.appmindlab.nano.pref_location_aware|false
> com.appmindlab.nano.pref_lux|false
> com.appmindlab.nano.pref_math_url|https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
> com.appmindlab.nano.pref_max_backup_count|2
> com.appmindlab.nano.pref_open_in_markdown|true
> com.appmindlab.nano.pref_order_by|modified
> com.appmindlab.nano.pref_order_by_direction|DESC
> com.appmindlab.nano.pref_preview_mode|off
> com.appmindlab.nano.pref_show_hidden|true
> com.appmindlab.nano.pref_theme|system
> ❘

The next build might fix it.  Give it a try.

**Comment by ippocratis** [comment]
Looks like fixed.
Auto Backup completed successfully.

**Comment by ippocratis** [comment]
Auto backup failures returned.on version 4.5.2m

**Comment by appml** [comment]
> Auto backup failures returned on version 4.5.2m

Does **Export Files** work?

If not, try Settings ➡️ Auto Backup ➡️ Pick the backup folder again

As far as I can tell, no major change to the backup logic since the fix earlier.

**Comment by ippocratis** [comment]
> > Auto backup failures returned on version 4.5.2m
> 
> Does **Export Files** work?
> 
Manually export works yes.

**Comment by appml** [comment]
> > > Auto backup failures returned on version 4.5.2m
> > 
> > 
> > Does **Export Files** work?
> 
> Manually export works yes.

Also see if disabling the ROM's Power Saver feature helps.

**Comment by ippocratis** [comment]
> Also see if disabling the ROM's Power Saver feature helps.

Thanks for the tip.
Maybe nextcloud app is also involved .
The mirror is a nextcloud mount.
I have rolled back to 4.5.2d for now and see how it goes.

Keep up
