### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [appml/neutrinote#82]
as https://mvnrepository.com/artifact/com.amulyakhare/com.amulyakhare.textdrawable is not in a [trusted maven repo](https://gitlab.com/fdroid/fdroidserver/-/blob/8cf4503a00f6e0ccb93f5a9089cf660f20b0045b/fdroidserver/scanner.py#L456-L480)

and https://mvnrepository.com/artifact/com.journeyapps/zxing-android-embedded on 3.5.0 and newer is

ref: https://monitor.f-droid.org/builds/log/com.appmindlab.nano/1341#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/7d80f891427cafa3ae2dfcf2a9b47be3196938fe

**Comment by appml** [comment]
Thanks.  Hopefully it's fixed in the next build (v4.5.3a).

**Comment by appml** [comment]
Build has resumed.  Thanks for the heads up.

**Comment by appml** [comment]
Closing as build has resumed.

**Comment by licaon-kter** [comment]
you should remove jcenter fyi, https://jfrog.com/blog/jcenter-sunset/
