### ISSUE TITLE
Autobackup/Mirror Not Working On WebDAV Mounts

### ISSUE THREAD

**Issue by Jmavd** [appml/neutrinote#84]
**Describe the bug**
Automatic Backups and Mirror are not working properly when the save location is located on a remote drive (Nextcloud instance).

Neutrinote itself reports that the backup occurs, and all files are created on the remote server, but all files are empty when attempting to access them through any means. This is tested not working both with the mount provided by the official Nextcloud app as well as DAVx5's WebDAV mount.

DAVx5 provides a notification for files as they are being uploaded, the notification for NeutriNote notes that are trying to upload never disappear (until the app is uninstalled, has its storage cleared, or the device reboots). The Nextcloud app thinks it has successfully uploaded the files, but reports the file size as 0 B (this is the reported file size no matter what backup technique is used).

Local file backup/mirror works perfectly fine, and moving the folder created from the backup to the network drive with the regular file manager succeeds, and all files are moved successfully. Mirroring is also affected by this issue.

**To Reproduce**
1. Go to Autobackup / Mirror in neutriNote Settings and enable it, setting the destination to a pre-configured Nextcloud or WebDAV android mount.
2.  Allow the backup to run.
3. The files appear on the remote server, but contain no content.

**Expected behavior**
Files will successfully backup/mirror, specifically, backed up files will have contents.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Graphene OS, android 13
 - App Version: tested on 4.5.3b 4.5.2m, and 4.5.2d

**Additional context**
This may be related to issue #80, but I tested on the version he had found success with (4.5.2d), and experienced the same issue. Additionally, I do not have power saving enabled, and I have tested this on a freshly installed version of the app (no customizations/hacks which could affect stability)

**Comment by ippocratis** [comment]
Same environment.

Davx5 and nextcloud webdav mounts.

Same behavior but random successful proper syncs.

Was thinking to also create an issue about this.

For now I just have my remote on local storage and sync that to my WebDAV storage.

**Comment by appml** [comment]
> **Describe the bug**
> Automatic Backups and Mirror are not working properly when the save location is located on a remote drive (Nextcloud instance).
> 
> Neutrinote itself reports that the backup occurs, and all files are created on the remote server, but all files are empty when attempting to access them through any means. This is tested not working both with the mount provided by the official Nextcloud app as well as DAVx5's WebDAV mount.
> 
> DAVx5 provides a notification for files as they are being uploaded, the notification for NeutriNote notes that are trying to upload never disappear (until the app is uninstalled, has its storage cleared, or the device reboots). The Nextcloud app thinks it has successfully uploaded the files, but reports the file size as 0 B (this is the reported file size no matter what backup technique is used).
> 
> Local file backup/mirror works perfectly fine, and moving the folder created from the backup to the network drive with the regular file manager succeeds, and all files are moved successfully. Mirroring is also affected by this issue.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to Autobackup / Mirror in neutriNote Settings and enable it, setting the destination to a pre-configured Nextcloud or WebDAV android mount.
> 2.  Allow the backup to run.
> 3. The files appear on the remote server, but contain no content.
> 
> **Expected behavior**
> Files will successfully backup/mirror, specifically, backed up files will have contents.
> 
> **Smartphone (please complete the following information):**
>  - Device: Google Pixel 4a
>  - OS: Graphene OS, android 13
>  - App Version: tested on 4.5.3b 4.5.2m, and 4.5.2d
> 
> **Additional context**
> This may be related to issue #80, but I tested on the version he had found success with (4.5.2d), and experienced the same issue. Additionally, I do not have power saving enabled, and I have tested this on a freshly installed version of the app (no customizations/hacks which could affect stability)
> 

Probably not a good idea to mount remote storage as the backup / mirroring algorithm is declared to the os as having a profile of minimal resource usage + low latency for local storage, rather than a remote sync mechanism.  

To achieve your goal, a dedicated sync solution might need to be involved.

**Comment by Jmavd** [comment]
Would there be any possibility of adding an option to allow changing the algorithm/usage profile or something similar to allow for synchronization to remote locations? I am trying to avoid dedicated sync solutions to minimize battery consumption, and have had success with other apps. Relatively little data is being synced, so it wouldn't greatly affect the actual sync times (I do something similar with Obsidian Vaults and my password manager), and a lot of utility would be gained, I don't think any other software currently available has the ability to do such synchronization. Neutrinote is basically perfect for my needs, barring the fact it cannot sync to network mounts.

**Comment by appml** [comment]
Please convert the issue to a feature request and feel free to work on the code. 

Doubtful any of the contributors had the bandwidth to provide that feature though.  Thanks.

**Comment by appml** [comment]
Not bug. To be filed as a sync module feature request.
