### ISSUE TITLE
"Back" fails to close the search widget.

### ISSUE THREAD

**Issue by GfEW** [appml/neutrinote#85]
**Describe the bug**
Whilst in any note, `Ctrl+F` opens search just fine, `Back` (or `Meta+Backspace`) fails to close search and get back to the note editor. 
Instead, it closes the entire note view and ends up in the notes list, which is counterintuitive and impractical. 
Supposedly, this behavior is also not compliant with android guidelines, as most apps that offer some kind of text based search at all, allow to close the search input widget by going `Back`, then showing the plain contents again that was shown before search was invoked.

**To Reproduce**
1. Open NeutrinoteCE on a device with external keyboard.
2. Open any note.
3. Press `Ctrl+F`.
4. optional: Enter some search term. 
5. Press `Back`, or `Meta+Backspace`.

Currently, this closes not just search input but the entire note view. 

**Expected behavior**
The search input widget should be closed but the note view still kept open, as it was before search was invoked.

**Smartphone (please complete the following information):**
 - Neutrinote CE 4.5.3c on various mobile devices from Android 9 to 11

**Comment by appml** [comment]
Thanks.  Should be included in the next release.

**Comment by GfEW** [comment]
As of v4.5.3e, this issue has been resolved. Thank you!
