### ISSUE TITLE
Version info missing in "About"

### ISSUE THREAD

**Issue by GfEW** [appml/neutrinote#87]
**Describe the bug**
Even if Neutrinote's version can be found in several ways (including adb, or android settings / installed apps / app info, or F-Droid), the natural place to look it up is the "About" item in Neutrinote's menu. In fact, there's an enormous amout of text to check for a possible version info, only to find nothing, after all.

**To Reproduce**
1. Open the main menu in NeutrinoteCE.
2. Tap (or press `Enter`) at "About".
3. Try to spot the version string.

Currently, no version string is provided there.

**Expected behavior**
The version should be provided, preferrably in a prominent, easy-to-spot manner in one of the first lines, e. g.
`  Neutrinote CE 4.5.3c  `
`       by App Mind      `.

**Smartphone (please complete the following information):**
 - Neutrinote CE 4.5.3c on various mobile devices from Android 9 to 11

**Comment by appml** [comment]
Version number already provided in the side bar.

HTH.

**Comment by GfEW** [comment]
Too bad I missed the version number there! It's written large and clear indeed.

Whilst obviously there's ignorance of mine to blame, I'm not particularly negligent with such details (rather the opposite), so this oversight might also indicate the version info placement isn't aligned with common UI principles very well. 

Version information is typically only looked up by the more techophile share of users every now and then. Normally, a prominent, general-purpose display area like the side bar header is "too valuable" to feature such specific information. OTOH, the _About_ section is by far the most commonly expected place to find the app name and version, along with the developer contact, licence and source repo address (if public), to name just the basics.

Therefore, I'd still maintain the suggestion to move (or at least include) the version info there.
