### ISSUE TITLE
Allow to reuse and refine search history items.

### ISSUE THREAD

**Issue by GfEW** [appml/neutrinote#88]
### Is your feature request related to a problem? Please describe.

As of Neutrinote CE 4.5.3c, the search widget allows to enter
* _either_ an entirely new search term
* _or_ a previously used search term from the search history drop down. 

In practice though, the previously used search term may have to be re-edited first, e. g. in order to change a date or to improve search syntax so it gives the intended results (especially with more elaborate searches comprised of multiple keywords, tags, globbing patterns etc.).

### Describe the solution you'd like

It should be possible to __insert any search term from history into the search box without submitting it__, to allow further adjustments. The solution should be available via touch or keyboard alike and not require overly arcane shortcuts:

__Preferred solution for touch input:__

* `Long-tap` at the search history item to insert it in the search box.

__Preferred solution for keyboard input:__

Once you've highlighted a particular item in the search history dropdown (using `Down`/`Up` cursor keys), either
* press the `Tab` key to insert the search term into the search box
(Note: This would alter the current behaviour where `Tab` apparently just acts as a duplicate of `Enter`.),

or
* press `Right` to insert the search term, and put the edit cursor to its right
* press `Left` to insert the search term, and put the cursor to its left.

### Describe alternatives you've considered

Two alternatives come to mind:

__(a)__ To reuse and refine a previous search (even if just a single character, quote etc. needs to be changed), type the entire search term anew.
--> This "workaround" is tediously cumbersome, especially with lengthy, complicated search terms.

__(b)__ Before submitting any search, mark the entire search term and copy it "just in case" you subsequently need to refine your search. In that case, paste the copied term back into the search box and re-edit, then submit it.
--> This "workaround" is tedious, as well, and moreover, __overwrites__ the current clipboard contents (which you might need otherwise) and __blocks you from using the clipboard__ in the meantime. The latter limitation is even more severe if you want to reuse and refine a search from longer ago.
--> Circumventing these complications by temporarily storing clipboard contents elsewhere would be _even more_ tedious.

Therefore, both "workarounds" are rather impractical, whilst the suggested solution would allow an elegant, efficient search workflow.

**Comment by appml** [comment]
Search string can already be reused.  Just click the arrow icon next to the search string to enter edit mode.

HTH.

**Comment by GfEW** [comment]
Thanks for the pointer, that's great news!

Even after reading your hint, I had to look twice to actually recognize those thin white-on-yellow arrows to the right of each item in the search history dropdown. Maybe it's a theme issue? In my instance of Neutrinote CE, their presentation is far too low-contrast to match the importance of the functionality they provide, making them an unfortunate example of non-evident UI design that requires "secret knowledge" to be fully utilized.

Here are two suggestions to improve this situation:
1. For __touch__ discoverability: 
Use higher contrast colors for the arrows, e. g. the same as for the search history items, i. e. black-on-white, or black-on-yellow at the highlighted row.
2. For __keyboard__ accessibility: 
Allow to reuse and adjust search history items by `Tab` or by `Left`/`Right`, as laid out in my OP.

Should I better file these suggestions in a new issue of their own, given that this one is closed already so they might get forgotten here?
