### ISSUE TITLE
Add ability to notify of a note at date/time

### ISSUE THREAD

**Issue by jm355** [appml/neutrinote#89]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use neutrinote as a todo list app (among other things), and I like to be able to set reminders for tasks and lists of tasks. 

**Describe the solution you'd like**
Say I'll need to do laundry on thursday at 17:00, I'd like to be able to make a new note that says laundry and get a system notification that shows the note filename and maybe a snippet of the note on thursday at 17:00

**Describe alternatives you've considered**
[The wiki](https://github.com/appml/nano/blob/master/index.md#snooze-experimental) mentions visual reminders as part of the snooze feature, but I don't know how to activate the reminders, and I'm not sure if they generate system notifications

**Additional context**
Thanks for the great app!

**Comment by appml** [comment]
Regarding the feature described in [here](https://appml.github.io/nano/#snooze), you would need to adjust the note's metadata with the syntax provided.

To save battery, unlikely a full blown notification will be provided.  However, you can always add any number of system alarm events for a note using **Paste to Calendar** function under 3-dot menu.

HTH.

**Comment by jm355** [comment]
I believe that there's a way to use android alarms to allow the system handle it, I'm not sure but I'm guessing the alarm wakes the app up to let it do what it needs to, like send a system notification of the note. I'll see if I can find some documentation on it

**Comment by jm355** [comment]
https://developer.android.com/develop/background-work/services/alarms/schedule here we go, there could be an option to set an inexact alarm or exact alarm, and warn the user that an exact one may use more battery

**Comment by jm355** [comment]
Not sure what mechanism is used for auto-backup, but it might be able to make use of the alarm mechanism too
