### ISSUE TITLE
Metadata not synchronized across devices

### ISSUE THREAD

**Issue by WPum** [appml/neutrinote#9]
To Reproduce:
1. Create a note on device A
2. Sync it to device B, and star it on device B
3. Sync it back to device A

Expected: note on device A is starred
Actual: note on device A is not starred. However, the note record in ~neutrinote_app_data.txt is updated

**Comment by appml** [comment]
@WPum Step 4 is needed: 

Side navigation bar -> **Restore App Data**

Hope this helps.

**Comment by WPum** [comment]
Yes, that works.
I'm using Syncthing and frequently change between devices. Can I set the app to automatically restore the data when changes are detected in ~neutrinote_app_data.txt (by modification time)?

**Comment by appml** [comment]
@WPum It is a little more complex than by comparing modification time and there seems not a fast scalable way to determine which versions contain the latest changes.
