### ISSUE TITLE
Emoji note names don't have text preview in note icon

### ISSUE THREAD

**Issue by jm355** [appml/neutrinote#94]
**Describe the bug**
Emoji note names don't have text preview in note icon

**To Reproduce**
1. make note
2. Rename note w/ emoji as first character
3. Go to list of notes
4. get tofu in icon

**Expected behavior**
Note icon shows emoji in it

**Screenshots**
![IMG_20241020_175559](https://github.com/user-attachments/assets/7a806c17-2382-4b59-bb84-94008010e0f8)

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: grapheneos
 - Browser: mull
 - Version: 4.5.3

**Comment by appml** [comment]
> **Describe the bug** Emoji note names don't have text preview in note icon
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. make note
> 2. Rename note w/ emoji as first character
> 3. Go to list of notes
> 4. get tofu in icon
> 
> **Expected behavior** Note icon shows emoji in it
> 
> **Screenshots** ![IMG_20241020_175559](https://private-user-images.githubusercontent.com/4341884/378240103-7a806c17-2382-4b59-bb84-94008010e0f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NjgwMjQsIm5iZiI6MTcyOTk2NzcyNCwicGF0aCI6Ii80MzQxODg0LzM3ODI0MDEwMy03YTgwNmMxNy0yMzgyLTRiNTktYmI4NC05NDAwODAxMGUwZjguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTgzNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFkMzk0M2Q4YjM1YmY1NGNlMjM5M2IxYTI1NTcwMmI5Y2Q2Y2FkMjM0NDJhYTRjZjdkYzdhYzJlOTIzNTBiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q7hoXKvC2ORyxf8bTkG3B2FHb_r0ALnRxhrTlLOCz1c)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Pixel 8
> * OS: grapheneos
> * Browser: mull
> * Version: 4.5.3

Fixed in the latest build.

**Comment by jm355** [comment]
Thanks!
