### ISSUE TITLE
On syncing, backups and mirroring

### ISSUE THREAD

**Issue by glow12121** [appml/neutrinote#95]
Hi,

Has anyone figured out how to synchronize NeutriNote writings in latest Androids, where apps cannot access other apps' folders in `Android/data/...`?

I know there is mirroring functionality in NeutriNote, but it seems to work one-way. I've just tried making the mirror folder `Downloads/MegaSync/`, but the list of writings in NeutriNote interface still only contains `Getting started.txt`.

Wouldn't it be better to allow the app to make some other folder its main working place, other than the one in `Android/data/com.appmindlab/files/`?

Plus, there is one tick for both mirroring and backups, whereas backups may not be needed. The cloud service Mega, for example, has its own backup functionality.

**Comment by appml** [comment]
> Hi,
> 
> Has anyone figured out how to synchronize NeutriNote writings in latest Androids, where apps cannot access other apps' folders in `Android/data/...`?
> 
> I know there is mirroring functionality in NeutriNote, but it seems to work one-way. I've just tried making the mirror folder `Downloads/MegaSync/`, but the list of writings in NeutriNote interface still only contains `Getting started.txt`.
> 
> Wouldn't it be better to allow the app to make some other folder its main working place, other than the one in `Android/data/com.appmindlab/files/`?
> 
> Plus, there is one tick for both mirroring and backups, whereas backups may not be needed. The cloud service Mega, for example, has its own backup functionality.

Mirroring is 2-way.  Please see if it is properly located under the [backup](https://appml.github.io/nano/#mirror:~:text=To%20activate%20the%20feature%2C%20simply%20add%20a%20folder%20under%20backup%20folder%20and%20name%20it%20mirror%2C%20Mirror%20Files%20will%20appear%20under%20the%20main%20note%20list%20menu%20with%20options%20to%20push%20and%20pull%20changes.) folder.

No. of backup copies can be controlled via this [string](https://appml.github.io/nano/#hacks:~:text=com.appmindlab.nano.pref_max_backup_count).

HTH.

**Comment by glow12121** [comment]
Understood, thank you!
